stages:
  train:
    cmd: python pretrained_model_tuner.py
    deps:
    - data/hymenoptera_data
    - pretrained_model_tuner.py
    params:
    - lr
    - momentum
    metrics:
    - results.json:
        cache: false
