stages:
  train:
    cmd: python pretrained_model_tuner.py
    deps:
      - data/hymenoptera_data
      - pretrained_model_tuner.py
    params:
      - lr
      - momentum
    outs:
      - model.pt:
          checkpoint: true
    live:
      dvclive:
        summary: true
        html: true
